apiVersion: v1
kind: Pod
metadata:
  name: sync-cert
  namespace: istio-gateway
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "sleep", "3600" ]
    volumeMounts:
    - name: certs
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
  - name: certs
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "certificate-from-aws"
