apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-private-repo
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/KoteshwarChinnolla/TECHLIFE-BACKEND.git
  username: KoteshwarChinnolla
  password: <GitHub Password>