apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxy-pods
  namespace: istio-system
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - hrms
  selector: {}
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 30s