apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: swagger-route
  namespace: hrms
spec:
  parentRefs:
    - name: gateway
      namespace: istio-gateway
  hostnames:
  - "hrms.anasolconsultancyservices.com"
  rules:
  - backendRefs:
    - name: attendance-service
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /swagger-ui/
    - path:
        type: PathPrefix
        value: /v3/
