apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: postgresql-tcp
  namespace: cnpg-system
spec:
  parentRefs:
  - name: gateway
    namespace: istio-gateway
    sectionName: postgress-listener
  rules:
  - backendRefs:
    - name: postgres-cluster-rw
      port: 5432